import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import { test } from 'node:test';
import { parse as parseYaml } from 'yaml';

function run(args: string[]) { return spawnSync(process.execPath, args, { cwd: process.cwd(), encoding: 'utf8' }); }

test('check resolves the configured preset as the single plugin source', () => {
  const result=run(['.harness/scripts/check.ts','--format','json']); assert.equal(result.status,0,result.stderr||result.stdout); const report=JSON.parse(result.stdout); assert.equal(report.harness_check,'PASS'); assert.equal(report.active_preset,'full-lifecycle'); assert.ok(report.active_plugins.includes('naming-frontend')); assert.ok(report.active_plugins.includes('tdd-workflow')); assert.ok(report.active_plugins.includes('pr-review'));
});
test('check exposes enforcement and keeps delegated checks non-blocking',()=>{const r=run(['.harness/scripts/check.ts','--format','json']);assert.equal(r.status,0,r.stderr||r.stdout);const p=JSON.parse(r.stdout);assert.equal(p.enforcement_policy.blocking,'machine-verified; violation blocks');assert.equal(p.summary.blocking_failed,0);assert.equal(p.summary.config_errors,0);assert.ok(p.summary.info>0);assert.equal(p.findings.find((x:any)=>x.check_id==='ts-typecheck')?.enforcement,'verifiable');});
test('active executable checks declare enforcement',()=>{const r=run(['.harness/scripts/check.ts','--format','json']);assert.equal(r.status,0,r.stderr||r.stdout);assert.equal(JSON.parse(r.stdout).summary.config_errors,0);});
test('minimal TypeScript baseline blocks ts-ignore',()=>{const plugin=parseYaml(fs.readFileSync('.harness/plugins/rules/typescript-strict.yaml','utf8')) as any;const noIgnore=plugin.checks.find((c:any)=>c.id==='ts-no-ignore');assert.equal(noIgnore.enforcement,'blocking');assert.equal(plugin.checks.find((c:any)=>c.id==='ts-no-explicit-any')?.enforcement,'verifiable');});

test('init-task creates empty v1.1 evidence',()=>{const id=`TEST-EVIDENCE-INIT-${process.pid}`;const dir=path.join('docs/wip',id);fs.rmSync(dir,{recursive:true,force:true});try{const r=run(['.harness/scripts/init-task.ts',id]);assert.equal(r.status,0,r.stderr||r.stdout);const e=JSON.parse(fs.readFileSync(path.join(dir,'evidence.json'),'utf8'));assert.equal(e.version,'1.1');assert.equal(e.task_id,id);assert.equal(e.updated_at,null);assert.deepEqual(e.gates,{});}finally{fs.rmSync(dir,{recursive:true,force:true});}});

test('evidence recorder binds a real gate to repository snapshot',()=>{const id=`TEST-EVIDENCE-GATE-${process.pid}`;const dir=path.join('docs/wip',id);fs.rmSync(dir,{recursive:true,force:true});try{assert.equal(run(['.harness/scripts/init-task.ts',id]).status,0);const rec=run(['.harness/scripts/evidence.ts',id,'--gate','check']);assert.equal(rec.status,0,rec.stderr||rec.stdout);const e=JSON.parse(fs.readFileSync(path.join(dir,'evidence.json'),'utf8'));assert.equal(e.gates.check.command,'npm run check');assert.equal(e.gates.check.result,'PASS');assert.match(e.gates.check.repository.commit_sha,/^[0-9a-f]{40}$/);assert.match(e.gates.check.repository.worktree_sha256,/^[0-9a-f]{64}$/);const verify=run(['.harness/scripts/evidence.ts',id,'--verify']);assert.notEqual(verify.status,0);assert.match(verify.stdout,/check: fresh PASS evidence present/);}finally{fs.rmSync(dir,{recursive:true,force:true});}});

test('evidence becomes stale when governed content changes',()=>{const id=`TEST-EVIDENCE-STALE-${process.pid}`;const dir=path.join('docs/wip',id);fs.rmSync(dir,{recursive:true,force:true});try{assert.equal(run(['.harness/scripts/init-task.ts',id]).status,0);assert.equal(run(['.harness/scripts/evidence.ts',id,'--gate','check']).status,0);fs.appendFileSync(path.join(dir,'changelog.md'),'- changed after evidence\n');const verify=run(['.harness/scripts/evidence.ts',id,'--verify']);assert.notEqual(verify.status,0);assert.match(verify.stderr,/check: stale evidence/);}finally{fs.rmSync(dir,{recursive:true,force:true});}});

test('review outputs do not invalidate machine evidence snapshot',()=>{const id=`TEST-REVIEW-EXCLUDE-${process.pid}`;const dir=path.join('docs/wip',id);fs.rmSync(dir,{recursive:true,force:true});try{assert.equal(run(['.harness/scripts/init-task.ts',id]).status,0);assert.equal(run(['.harness/scripts/evidence.ts',id,'--gate','check']).status,0);fs.writeFileSync(path.join(dir,'review-packet.md'),'review packet\n');fs.writeFileSync(path.join(dir,'independent-review.json'),'{}\n');const verify=run(['.harness/scripts/evidence.ts',id,'--verify']);assert.match(verify.stdout,/check: fresh PASS evidence present/);}finally{fs.rmSync(dir,{recursive:true,force:true});}});

test('v1.0 evidence cannot be reused as v1.1',()=>{const id=`TEST-EVIDENCE-MIGRATION-${process.pid}`;const dir=path.join('docs/wip',id);fs.rmSync(dir,{recursive:true,force:true});try{assert.equal(run(['.harness/scripts/init-task.ts',id]).status,0);fs.writeFileSync(path.join(dir,'evidence.json'),JSON.stringify({version:'1.0',task_id:id,updated_at:new Date().toISOString(),gates:{check:{}}}));const verify=run(['.harness/scripts/evidence.ts',id,'--verify']);assert.notEqual(verify.status,0);assert.match(verify.stderr,/v1\.0 evidence is stale by definition/);}finally{fs.rmSync(dir,{recursive:true,force:true});}});

test('independent review requires a separate reviewer session and fresh snapshot',()=>{const id=`TEST-INDEPENDENT-REVIEW-${process.pid}`;const dir=path.join('docs/wip',id);fs.rmSync(dir,{recursive:true,force:true});try{assert.equal(run(['.harness/scripts/init-task.ts',id]).status,0);const prepare=run(['.harness/scripts/independent-review.ts',id,'--prepare']);assert.equal(prepare.status,0,prepare.stderr||prepare.stdout);const packet=fs.readFileSync(path.join(dir,'review-packet.md'),'utf8');const commit=packet.match(/- commit: ([0-9a-f]{40})/)?.[1];const worktree=packet.match(/- worktree: ([0-9a-f]{64})/)?.[1];assert.ok(commit&&worktree);fs.writeFileSync(path.join(dir,'independent-review.json'),JSON.stringify({version:'1.0',task_id:id,builder:{session_id:'same'},reviewer:{kind:'codex-fresh-context',session_id:'same'},repository:{commit_sha:commit,worktree_sha256:worktree},reviewed_at:new Date().toISOString(),verdict:'PASS',findings:[],notes:'reviewed'},null,2));const rejected=run(['.harness/scripts/independent-review.ts',id,'--verify']);assert.notEqual(rejected.status,0);assert.match(rejected.stderr,/reviewer session must differ/);const record=JSON.parse(fs.readFileSync(path.join(dir,'independent-review.json'),'utf8'));record.reviewer.session_id='fresh-reviewer';fs.writeFileSync(path.join(dir,'independent-review.json'),JSON.stringify(record,null,2));const accepted=run(['.harness/scripts/independent-review.ts',id,'--verify']);assert.equal(accepted.status,0,accepted.stderr||accepted.stdout);}finally{fs.rmSync(dir,{recursive:true,force:true});}});

test('independent review becomes stale after governed content changes',()=>{const id=`TEST-INDEPENDENT-STALE-${process.pid}`;const dir=path.join('docs/wip',id);fs.rmSync(dir,{recursive:true,force:true});try{assert.equal(run(['.harness/scripts/init-task.ts',id]).status,0);assert.equal(run(['.harness/scripts/independent-review.ts',id,'--prepare']).status,0);const packet=fs.readFileSync(path.join(dir,'review-packet.md'),'utf8');const commit=packet.match(/- commit: ([0-9a-f]{40})/)?.[1];const worktree=packet.match(/- worktree: ([0-9a-f]{64})/)?.[1];fs.writeFileSync(path.join(dir,'independent-review.json'),JSON.stringify({version:'1.0',task_id:id,builder:{session_id:'builder'},reviewer:{kind:'human',session_id:'reviewer'},repository:{commit_sha:commit,worktree_sha256:worktree},reviewed_at:new Date().toISOString(),verdict:'PASS',findings:[]},null,2));fs.appendFileSync(path.join(dir,'changelog.md'),'- mutation after review\n');const verify=run(['.harness/scripts/independent-review.ts',id,'--verify']);assert.notEqual(verify.status,0);assert.match(verify.stderr,/stale/);}finally{fs.rmSync(dir,{recursive:true,force:true});}});

test('init-task rejects traversal-like task identifiers',()=>{const r=run(['.harness/scripts/init-task.ts','../escape']);assert.notEqual(r.status,0);assert.match(r.stderr,/Invalid task ID/);});
test('self-review rejects malformed task identifiers',()=>{const r=run(['.harness/scripts/self-review.ts','../escape']);assert.notEqual(r.status,0);assert.match(r.stderr,/Invalid task id/);});
test('independent-review rejects malformed task identifiers',()=>{const r=run(['.harness/scripts/independent-review.ts','../escape','--verify']);assert.notEqual(r.status,0);assert.match(r.stderr,/Usage/);});
